import './api/ident';
import './api/underscoreIdent';
import './api/number';
import './api/cNumber';
import './api/binaryNumber';
import './api/starters';
import './api/getLanguage';
import './api/highlight';
//import './api/fixmarkup';
